version: '3.9'

services:
   server:
      build: ./backend
      container_name: snakes-ladders-server
      ports:
         - "4000:4000"
      env_file:
         - ./backend/.env
      networks:
        - snakes-ladders-net
      restart: unless-stopped
   client:
      build:
        context: ./client
        args:
          VITE_SERVER_URL: ${VITE_SERVER_URL}
      container_name: snakes-ladders-client
      ports:
        - '5174:5173'
      networks:
        - snakes-ladders-net
      depends_on:
        - server
      restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge